#!/usr/bin/env bash
echo "This script to put files."

# Check for bucket name argument
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg.. my-bucket-name."
    exit 1
fi

# Check for filename argument
if [ -z "$2" ]; then
    echo "There needs to be a filename."
    exit 1
fi

BUCKET_NAME=$1
FILENAME=$2
OBJECT_KEY=$(basename $FILENAME)

aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILENAME \
--key $OBJECT_KEY