#!/usr/bin/env bash
echo "This script to sync files."

# Exit immediately if any command return a non-zero status
set -e

# Check for bucket name argument
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg.. my-bucket-name."
    exit 1
fi

# Check for filename prefix argument
if [ -z "$2" ]; then
    echo "There needs to be a filename prefix."
    exit 1
fi

BUCKET_NAME=$1
FILENAME_PREFIX=$2
OUTPUT_DIR="/tmp/s3-bash-script"

# Remove folder if it already exists
rm -r $OUTPUT_DIR

# Lets create output folder
mkdir -p $OUTPUT_DIR

# Generate a random number to determine how many files to create
NUM_FILES=$((RANDOM % 6 + 5))

for((i = 1; i <= $NUM_FILES; i++)); do
    # Generate a random filename
    FILENAME="$OUTPUT_DIR/${FILENAME_PREFIX}_$i.txt"
    # Generate random data and write it to the file
    dd if=/dev/urandom of=$FILENAME bs=1024 count=$((RANDOM % 1024 + 1)) &> /dev/null
done

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/$FILENAME_PREFIX/