#!/usr/bin/env bash
echo "Deploy s3 bucket using CloudFormation."

STACK_NAME="cfn-s3-bucket-simple-01"
#https://docs.aws.amazon.com/cli/latest/reference/cloudformation/deploy.html
aws cloudformation deploy \
--template-file template.yaml \
--region us-east-1 \
--stack-name $STACK_NAME