#!/usr/bin/env bash
echo "This script creates an S3 bucket."

# Check for bucket name argument
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg.. my-bucket-name."
    exit 1
fi

BUCKET_NAME=$1

aws s3api create-bucket \
--bucket $BUCKET_NAME \
--region us-east-1 \
--query Location \
--output text